# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-26 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_foo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foo',
            new_name='FooORM',
        ),
    ]
